# Site settings
title: Portfolio | Baloran
email: contact@baloran.fr
description: "Coming soon the real portfolio"
baseurl: ""
url: ""
twitter_username: bal0ran
github_username:  baloran

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
